In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('final_wrangled.csv')

In [3]:
df.head()

Unnamed: 0         0       1    2    3     4      5    6      7    8  ...  \
0           0  1.632387     0.0  0.0  0.0  36.0  467.0  0.0  128.0  0.0  ...   
1           1  2.397531  2621.0  0.0  0.0  36.0  467.0  0.0  128.0  0.0  ...   
2           2  2.397531  2621.0  0.0  0.0  36.0  467.0  0.0  128.0  0.0  ...   
3           3  2.397531  2621.0  0.0  0.0  36.0  467.0  0.0  128.0  0.0  ...   
4           4  2.397531  2621.0  0.0  0.0  36.0  467.0  0.0  128.0  0.0  ...   

      18   19     20   21   22   23   24   25   26        27  
0  467.0  0.0  128.0  0.0  0.0  0.0  0.0  0.0  0.0  2.397531  
1  467.0  0.0  128.0  0.0  0.0  0.0  0.0  0.0  0.0  2.397531  
2  467.0  0.0  128.0  0.0  0.0  0.0  0.0  0.0  0.0  2.397531  
3  467.0  0.0  128.0  0.0  0.0  0.0  0.0  0.0  0.0  2.397531  
4  512.0  0.0  128.0  0.0  0.0  0.0  0.0  0.0  0.0  1.678357  

[5 rows x 29 columns]

In [4]:
df=df.drop('Unnamed: 0',axis=1)

In [5]:
df.head()

0       1    2    3     4      5    6      7    8    9  ...     18  \
0  1.632387     0.0  0.0  0.0  36.0  467.0  0.0  128.0  0.0  0.0  ...  467.0   
1  2.397531  2621.0  0.0  0.0  36.0  467.0  0.0  128.0  0.0  0.0  ...  467.0   
2  2.397531  2621.0  0.0  0.0  36.0  467.0  0.0  128.0  0.0  0.0  ...  467.0   
3  2.397531  2621.0  0.0  0.0  36.0  467.0  0.0  128.0  0.0  0.0  ...  467.0   
4  2.397531  2621.0  0.0  0.0  36.0  467.0  0.0  128.0  0.0  0.0  ...  512.0   

    19     20   21   22   23   24   25   26        27  
0  0.0  128.0  0.0  0.0  0.0  0.0  0.0  0.0  2.397531  
1  0.0  128.0  0.0  0.0  0.0  0.0  0.0  0.0  2.397531  
2  0.0  128.0  0.0  0.0  0.0  0.0  0.0  0.0  2.397531  
3  0.0  128.0  0.0  0.0  0.0  0.0  0.0  0.0  2.397531  
4  0.0  128.0  0.0  0.0  0.0  0.0  0.0  0.0  1.678357  

[5 rows x 28 columns]

In [6]:
X_train=df.drop('27',axis=1)
y_train=df['27']

In [7]:
from sklearn.preprocessing import StandardScaler


In [8]:
scaler=StandardScaler()
X_scaled=scaler.fit_transform(X_train)
X_train=X_scaled

In [135]:
import numpy as np
import os
import cv2
import keras
from keras.utils import np_utils
from keras.models import Sequential
from keras.layers import Conv2D,MaxPooling2D,Dense,Flatten,Dropout

In [136]:
model=Sequential()
model.add(keras.Input(shape=(27,)))
model.add(Dense(500,activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(1,activation='relu'))
model.summary()

Model: "sequential_13"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_27 (Dense)            (None, 500)               14000     
                                                                 
 dropout_14 (Dropout)        (None, 500)               0         
                                                                 
 dense_28 (Dense)            (None, 1)                 501       
                                                                 
Total params: 14,501
Trainable params: 14,501
Non-trainable params: 0
_________________________________________________________________


In [137]:
model.compile(loss='mean_absolute_percentage_error', optimizer='adam', metrics=['mse'])

In [138]:
model.fit(X_train,y_train,epochs=20,verbose=1)

Epoch 1/20
317/317 [==============================] - 0s 834us/step - loss: 13.6730 - mse: 0.7313
Epoch 2/20
317/317 [==============================] - 0s 851us/step - loss: 4.8342 - mse: 0.0775
Epoch 3/20
317/317 [==============================] - 0s 891us/step - loss: 4.1047 - mse: 0.0526
Epoch 4/20
317/317 [==============================] - 0s 877us/step - loss: 3.7298 - mse: 0.0450
Epoch 5/20
317/317 [==============================] - 0s 860us/step - loss: 3.9181 - mse: 0.0554
Epoch 6/20
317/317 [==============================] - 0s 936us/step - loss: 3.3696 - mse: 0.0356
Epoch 7/20
317/317 [==============================] - 0s 892us/step - loss: 3.2116 - mse: 0.0322
Epoch 8/20
317/317 [==============================] - 0s 856us/step - loss: 3.2626 - mse: 0.0680
Epoch 9/20
317/317 [==============================] - 0s 944us/step - loss: 3.0958 - mse: 0.0295
Epoch 10/20
317/317 [==============================] - 0s 859us/step - loss: 3.0434 - mse: 0.0281
Epoch 11/20
317/317 [=======

In [139]:
model

In [140]:
test=np.array([X_train[100]])
test=test[None:]
model.predict(test)

array([[5.452319]], dtype=float32)

In [141]:
test

array([[ 1.52489918, -0.17100584,  0.56377844,  0.47407922,  4.46122811,
        -0.54041788,  2.86830783, 12.66308082,  3.20128922, -0.13643885,
         0.3797529 ,  0.42404271,  0.38061286,  0.41964944, -0.21623113,
         0.97553759,  2.02816775,  4.10084607,  2.6809851 ,  2.86830783,
         0.01542448, -0.14105741,  3.50805696,  0.4785097 ,  0.50929021,
         0.46623327,  0.50515716]])

In [142]:
X_train

array([[ -2.005974  , -57.92872789,  -5.43668291, ...,  -0.7469887 ,
         -0.74597154,  -0.74595583],
       [ -1.13920957,  -0.17100584,  -5.43668291, ...,  -0.7469887 ,
         -0.74597154,  -0.74595583],
       [ -1.13920957,  -0.17100584,  -5.43668291, ...,  -0.7469887 ,
         -0.74597154,  -0.74595583],
       ...,
       [ -0.69262657,   0.13750545,  -0.50669923, ...,  -0.7469887 ,
         -0.74597154,  -0.74595583],
       [ -0.72921225,   0.13750545,  -0.5298447 , ...,  -0.7469887 ,
         -0.74597154,  -0.74595583],
       [ -0.72775807,   0.13750545,  -0.4777674 , ...,  -0.7469887 ,
         -0.74597154,  -0.74595583]])

In [143]:
model.save('behavourial_model.h5')

In [144]:
preds=model.predict(X_train[None:])

In [145]:
a=[]
for i in preds:
    if i>5:
        a.append(i)

In [146]:
len(a)

789

In [147]:
len(preds)

10113

In [148]:
preds

array([[17.211504 ],
       [ 2.9041867],
       [ 2.9041867],
       ...,
       [ 2.7947564],
       [ 2.791092 ],
       [ 2.7912602]], dtype=float32)

In [149]:
from pickle import dump